name = "webbios-storefront-engine"
main = "src/index.tsx"
compatibility_date = "2024-03-20"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "webbios_db"
database_id = "fd1e1975-5699-4587-a065-1533c3fafa48"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "a97c87f45d53428aac9e66738a9bfc9f"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "webbios-platform"
